

const  UPDATE_USER=`UPDATE_USER`
const  UPDATE_COUNTRY_INFO=`UPDATE_COUNTRY_INFO`
const  UPDATE_ALL_CLASSIFIEDS=`UPDATE_ALL_CLASSIFIEDS`
const  UPDATE_SELECTED_CLASSIFIEDS=`UPDATE_SELECTED_CLASSIFIEDS`


export {UPDATE_USER, UPDATE_COUNTRY_INFO,UPDATE_ALL_CLASSIFIEDS,UPDATE_SELECTED_CLASSIFIEDS};


export const CURRENCIES=[`R`, `XFA`,`FCFA`,`$`, `¥`, `₹`,`﷼`, `£`, `₩`];